version: "3.8"

services:
  sdk-parser:
    build: .
    user: "${UID}:${GID}"
    command: python main.py
    volumes:
      - ./app:/usr/src/app
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474"]
      interval: 5s
      timeout: 10s
      retries: 5
